<template>
  <div class="loadingio-spinner-spinner-0jschtevpxqr">
    <div class="ldio-2jhbotil80s">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<style scoped type="text/css">
@keyframes ldio-2jhbotil80s {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-2jhbotil80s div {
  left: 89.3px;
  top: 72.2px;
  position: absolute;
  animation: ldio-2jhbotil80s linear 3.571428571428571s infinite;
  background: #1d3f72;
  width: 11.399999999999999px;
  height: 22.799999999999997px;
  border-radius: 5.699999999999999px / 11.399999999999999px;
  transform-origin: 5.699999999999999px 22.799999999999997px;
}
.ldio-2jhbotil80s div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -3.061224489795918s;
  background: #1d3f72;
}
.ldio-2jhbotil80s div:nth-child(2) {
  transform: rotate(51.42857142857143deg);
  animation-delay: -2.5510204081632653s;
  background: #5699d2;
}
.ldio-2jhbotil80s div:nth-child(3) {
  transform: rotate(102.85714285714286deg);
  animation-delay: -2.040816326530612s;
  background: #d8ebf9;
}
.ldio-2jhbotil80s div:nth-child(4) {
  transform: rotate(154.28571428571428deg);
  animation-delay: -1.530612244897959s;
  background: #71c2cc;
}
.ldio-2jhbotil80s div:nth-child(5) {
  transform: rotate(205.71428571428572deg);
  animation-delay: -1.020408163265306s;
  background: #4996a2;
}
.ldio-2jhbotil80s div:nth-child(6) {
  transform: rotate(257.14285714285717deg);
  animation-delay: -0.510204081632653s;
  background: #785471;
}
.ldio-2jhbotil80s div:nth-child(7) {
  transform: rotate(308.57142857142856deg);
  animation-delay: 0s;
  background: #e8cdc5;
}
.loadingio-spinner-spinner-0jschtevpxqr {
  width: 190px;
  height: 190px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-2jhbotil80s {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-2jhbotil80s div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>